#ifndef RAYTRACING_BASE_H
#define RAYTRACING_BASE_H


// Enum
enum RayTracing_SuperSampling_Method {
	RAYTRACING_SUPERSAMPLING_GRID = 0,
	RAYTRACING_SUPERSAMPLING_RANDOM,
	RAYTRACING_SUPERSAMPLING_JITTER,
	RAYTRACING_SUPERSAMPLING_ADAPTIVE,
	RAYTRACING_SUPERSAMPLING_MAX,
	RAYTRACING_SUPERSAMPLING_NONE
};


#endif  // RAYTRACING_BASE_H
